### ISSUE TITLE
Issue: DLC Installers / XBlastOS XBE will not boot

### ISSUE THREAD

**Issue by Laserdisc9X** [Ryzee119/LithiumX#9] opened 2022-12-16 17:15 UTC
Hi,  first of all I would like to preface by saying I love LithiumX and use it as my main dashboard;  I really appreciate all the work you've done with it.

I've attempted this on two XBOXs,  the first a 1.1 and the other a 1.4;  LithiumX fails to launch **any** of the DLC Installers (Digiex ver.) and XBlastOS (XBE ver.),  however the installers **will boot** with UnleashX and XBMC.

**DLC** installed to **F:\DLC\\[DLC NAME]\default.xbe**.
**XBlast** installed to **E:\Apps\XblastOS\default.xbe**.

Are you able to replicate this? known issue?  --  Either way, I hope this will help.

**Comment by Ryzee119** [comment] 2022-12-17 19:42
Thanks for the report.
What bios are you using?

**Comment by Laserdisc9X** [comment] 2022-12-18 07:42
Both are using Cerbios 2.1.0 Beta (the latest of this reply).   Apologies for not reporting that originally.

**Comment by Ryzee119** [comment] 2022-12-18 07:44
Can you confirm they launch using another dashboard? 
I've heard cerb may have issues with DLC installers

**Comment by Laserdisc9X** [comment] 2022-12-18 07:57
DLC and XBlast launch with UnleashX on Cerbios;   I just recently formatted a new SSD and installed some, this is how I came to notice the issue.   Found the XBlast issue when upgrading my Bios to UDMA-5 version of Cerbios.

**Comment by Laserdisc9X** [comment] 2023-01-01 04:38
Just wanted to report that on the new Cerbios 2.2.0 Beta,  XBlastOS is launching under LithiumX;   No change for DLC.

Happy holidays.

**Comment by Ryzee119** [comment] 2023-06-15 05:13
Could you please retest in V0.9

**Comment by LoveMHz** [comment] 2024-01-14 20:44
I'm unable to reproduce this issue with ``v0.9.3``

Maybe we should consider closing this issue for now?

**Comment by Ryzee119** [comment] 2024-01-14 21:18
I was never able to repo either.
Will close for now. Can raise a new issue if this occurs

**Closed as completed** 2024-01-14 21:18 UTC
